### ISSUE TITLE
Research Report 2

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/UASB#88]
Hey @juanchon998 our research report is linked below, thanks again for editing it.  One area that would be great for you to look over is the functions (do they make sense, should we add more).

[Here it is](https://github.com/AguaClara/UASB/blob/master/summer2018report.md)

Also a random fluids question, but the minor loss coefficient for a straight pipe is just 1, right?

**Comment by juanchon998** [comment]
I will grade it today! Technically there is no minor loss for a straight pipe. If you use [the head loss trick](https://aguaclara.github.io/Textbook/Review/Review_Fluid_Mechanics.html#head-loss-elevation-difference-trick), then yes the minor loss coefficient for a straight pipe becomes 1!

**Comment by isakaminsky** [comment]
- [ ] Line number 83: Sorry to nitpick here, but a 5 gallon bucket is actually 19 liters not 20, which you mentioned in the table above!
**A five gallon bucket can hold slightly more than 20 L because the 5 gallons doesn't refer to filling it all the way to the top. So maybe we need to include something about that?**

**Comment by ananya-gangadhar** [comment]
So @juanchon998, do you suggest that we should refer to it in the report still as "head loss trick" but embed a link to the textbook?

**Comment by juanchon998** [comment]
As of now I would recommend referring to it once as "head loss trick," linking it to the textbook, and saying that it will be used throughout the rest of the document (then not mentioning it again). Basically I want it to be clear to the reader that we are using the head loss trick while also minimizing the uses of the the phrase "head loss trick." If you come up with another way of accomplishing that then definitely use that!

**Comment by IanCullings** [comment]
More edits before the end of the summer:
- [ ] The biogas capture system should be updated following our meeting with Ed as to our plan for implementation there
- [ ] We should add figures of our proposed capture system (use google drawings!)
- [ ] There should at least be a mention of the type of biogas bag used
- [ ] Check all images work (both in this report and the Spring 2018 report) once the repo is reorganized

**Comment by IanCullings** [comment]
More tasks:

- [ ] Add tapioca test video/image to report
- [ ] Add tipping bucket frame design video to report and fabrication manual

**Comment by ananya-gangadhar** [comment]
**TASKS FOR  [FINAL SUMMER REPORT](https://github.com/AguaClara/UASB/blob/master/Reports%20and%20Manuals/summer2018report.md)***
***Ian***
- [ ] Fill in the Biogas Lid Design sections
- [ ] Add info under Future Work--->Quantifying Biogas Production
- [ ] Add info under Future Work--->Effluent Line Geometry
- [ ] Make doctests (if possible)

***Ananya***
- [ ] Add info under Future Work--->Choosing Tank for Reactor
- [ ] Add info under Future Work--->Removal of FOG
- [ ] Put comments with result values for every relevant code block
- [ ] Do final review and fix image and table numbers
- [ ] Remake PDF for spring 2018 manual and fix broken links
